# Gateway API 网关服务部署 - 简化版本
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: voicehelper
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: voicehelper
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/component: api-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
        app.kubernetes.io/component: api-gateway
        app.kubernetes.io/part-of: voicehelper
    spec:
      containers:
      - name: gateway
        image: voicehelper/gateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: grpc
        env:
        - name: PORT
          value: "8080"
        - name: GRPC_PORT
          value: "8081"
        - name: GIN_MODE
          value: "release"
        - name: LOG_LEVEL
          value: "info"
        - name: CORS_ORIGINS
          value: "*"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: voicehelper-secrets
              key: JWT_SECRET
        - name: ADMIN_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: admin-secret
        # 数据库连接
        - name: POSTGRES_HOST
          value: "postgresql-service.voicehelper.svc.cluster.local"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "voicehelper"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: voicehelper-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: voicehelper-secrets
              key: POSTGRES_PASSWORD
        # Redis连接
        - name: REDIS_HOST
          value: "redis-service.voicehelper.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: voicehelper-secrets
              key: REDIS_PASSWORD
        # 服务发现
        - name: ALGO_SERVICE_URL
          value: "http://algo-service.voicehelper.svc.cluster.local:8000"
        - name: VOICE_SERVICE_URL
          value: "http://voice-service.voicehelper.svc.cluster.local:8001"
        - name: BGE_SERVICE_URL
          value: "http://bge-service.voicehelper.svc.cluster.local:8080"
        - name: FAISS_SERVICE_URL
          value: "http://faiss-service.voicehelper.svc.cluster.local:8081"
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
# Gateway 服务
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: voicehelper
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: voicehelper
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: grpc
  selector:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: api-gateway
