# FAISS 向量搜索服务部署 - 简化版本
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: faiss-service
  namespace: voicehelper
  labels:
    app.kubernetes.io/name: faiss-service
    app.kubernetes.io/component: vector-search
    app.kubernetes.io/part-of: voicehelper
spec:
  serviceName: faiss-service
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: faiss-service
      app.kubernetes.io/component: vector-search
  template:
    metadata:
      labels:
        app.kubernetes.io/name: faiss-service
        app.kubernetes.io/component: vector-search
        app.kubernetes.io/part-of: voicehelper
    spec:
      containers:
      - name: faiss-service
        image: voicehelper/faiss-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: PORT
          value: "8081"
        - name: FAISS_INDEX_TYPE
          value: "IVF"
        - name: FAISS_NLIST
          value: "100"
        - name: FAISS_NPROBE
          value: "10"
        - name: VECTOR_DIMENSION
          value: "1024"
        - name: INDEX_SAVE_INTERVAL
          value: "300"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: faiss-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: faiss-data
      labels:
        app.kubernetes.io/name: faiss-service
        app.kubernetes.io/component: storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: voicehelper-ssd
---
# FAISS 服务
apiVersion: v1
kind: Service
metadata:
  name: faiss-service
  namespace: voicehelper
  labels:
    app.kubernetes.io/name: faiss-service
    app.kubernetes.io/component: vector-search
    app.kubernetes.io/part-of: voicehelper
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: faiss-service
    app.kubernetes.io/component: vector-search
---
# FAISS 客户端服务
apiVersion: v1
kind: Service
metadata:
  name: faiss-client
  namespace: voicehelper
  labels:
    app.kubernetes.io/name: faiss-service
    app.kubernetes.io/component: client
    app.kubernetes.io/part-of: voicehelper
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: faiss-service
    app.kubernetes.io/component: vector-search
