# VoiceHelper AI - 开发环境 Docker Compose 配置
# 使用方法: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d

version: '3.8'

services:
  # ===========================================
  # 开发环境特定配置
  # ===========================================

  # Go API 网关 - 开发模式
  gateway:
    build:
      target: builder  # 使用构建阶段，支持热重载
    environment:
      - GIN_MODE=debug
      - LOG_LEVEL=debug
    volumes:
      - ./backend:/app:cached
      - gateway_go_cache:/go/pkg/mod
    command: ["go", "run", "./cmd/gateway"]

  # Python 算法服务 - 开发模式
  algo-service:
    build:
      target: base  # 使用基础阶段
    environment:
      - LOG_LEVEL=debug
      - PYTHONUNBUFFERED=1
    volumes:
      - ./algo:/app:cached
      - algo_pip_cache:/root/.cache/pip
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  # 语音处理服务 - 开发模式
  voice-service:
    build:
      target: base
    environment:
      - LOG_LEVEL=debug
      - PYTHONUNBUFFERED=1
    volumes:
      - ./algo:/app:cached
    command: ["python", "-m", "uvicorn", "services.voice_service:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  # Next.js 前端 - 开发模式
  frontend:
    build:
      target: deps  # 使用依赖阶段
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080
    volumes:
      - ./platforms/web:/app:cached
      - frontend_node_modules:/app/node_modules
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"

  # 开发者门户 - 开发模式
  developer-portal:
    build:
      target: deps
    environment:
      - NODE_ENV=development
    volumes:
      - ./developer-portal:/app:cached
      - portal_node_modules:/app/node_modules
    command: ["npm", "run", "dev"]

  # 管理后台 - 开发模式
  admin:
    build:
      context: ./platforms/admin
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./platforms/admin:/app:cached

  # ===========================================
  # 开发工具
  # ===========================================

  # 代码质量检查
  code-quality:
    image: python:3.11-slim
    container_name: voicehelper-code-quality
    working_dir: /app
    volumes:
      - .:/app:cached
    command: ["sleep", "infinity"]
    networks:
      - voicehelper-network
    profiles:
      - tools

  # 数据库迁移工具
  db-migrate:
    image: migrate/migrate:latest
    container_name: voicehelper-db-migrate
    volumes:
      - ./tools/deployment/database/migrations:/migrations
    command: ["sleep", "infinity"]
    networks:
      - voicehelper-network
    profiles:
      - tools

# ===========================================
# 开发环境数据卷
# ===========================================
volumes:
  # 开发缓存卷
  gateway_go_cache:
    driver: local
  algo_pip_cache:
    driver: local
  frontend_node_modules:
    driver: local
  portal_node_modules:
    driver: local
