# VoiceHelper AI - Dify 集成配置
# 使用方法: docker-compose -f docker-compose.yml -f docker-compose.dify.yml up -d

version: '3.8'

services:
  # ===========================================
  # 🤖 Dify AI 平台服务
  # ===========================================

  # Dify PostgreSQL 数据库 (独立实例)
  dify-postgres:
    image: postgres:15-alpine
    container_name: voicehelper-dify-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DIFY_POSTGRES_DB:-dify}
      POSTGRES_USER: ${DIFY_POSTGRES_USER:-dify}
      POSTGRES_PASSWORD: ${DIFY_POSTGRES_PASSWORD:-dify123}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "${DIFY_POSTGRES_PORT:-5433}:5432"
    volumes:
      - dify_postgres_data:/var/lib/postgresql/data
      - ./tools/deployment/dify/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - voicehelper-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DIFY_POSTGRES_USER:-dify} -d ${DIFY_POSTGRES_DB:-dify}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Dify Redis (独立实例)
  dify-redis:
    image: redis:7-alpine
    container_name: voicehelper-dify-redis
    restart: unless-stopped
    command: redis-server --requirepass ${DIFY_REDIS_PASSWORD:-dify123} --appendonly yes
    ports:
      - "${DIFY_REDIS_PORT:-6380}:6379"
    volumes:
      - dify_redis_data:/data
    networks:
      - voicehelper-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${DIFY_REDIS_PASSWORD:-dify123}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Dify Weaviate 向量数据库
  dify-weaviate:
    image: semitechnologies/weaviate:1.21.8
    container_name: voicehelper-dify-weaviate
    restart: unless-stopped
    environment:
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=false
      - AUTHENTICATION_APIKEY_ENABLED=true
      - AUTHENTICATION_APIKEY_ALLOWED_KEYS=${DIFY_WEAVIATE_API_KEY:-WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih}
      - AUTHENTICATION_APIKEY_USERS=hello@dify.ai
      - AUTHORIZATION_ADMINLIST_ENABLED=true
      - AUTHORIZATION_ADMINLIST_USERS=hello@dify.ai
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=none
      - CLUSTER_HOSTNAME=node1
    ports:
      - "${DIFY_WEAVIATE_PORT:-8080}:8080"
    volumes:
      - dify_weaviate_data:/var/lib/weaviate
    networks:
      - voicehelper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Dify Sandbox (代码执行环境)
  dify-sandbox:
    image: langgenius/dify-sandbox:0.2.1
    container_name: voicehelper-dify-sandbox
    restart: unless-stopped
    environment:
      - API_KEY=${DIFY_SANDBOX_API_KEY:-dify-sandbox}
      - GIN_MODE=release
      - WORKER_TIMEOUT=15
    ports:
      - "${DIFY_SANDBOX_PORT:-8194}:8194"
    volumes:
      - dify_sandbox_data:/dependencies
    networks:
      - voicehelper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8194/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Dify API 服务
  dify-api:
    image: langgenius/dify-api:0.6.16
    container_name: voicehelper-dify-api
    restart: unless-stopped
    environment:
      # 基础配置
      - MODE=api
      - LOG_LEVEL=${DIFY_LOG_LEVEL:-INFO}
      - SECRET_KEY=${DIFY_SECRET_KEY:-your-dify-secret-key-here}
      - INIT_PASSWORD=${DIFY_INIT_PASSWORD:-password123}
      - CONSOLE_WEB_URL=${DIFY_CONSOLE_WEB_URL:-http://localhost:3001}
      - CONSOLE_API_URL=${DIFY_CONSOLE_API_URL:-http://localhost:5001}
      - SERVICE_API_URL=${DIFY_SERVICE_API_URL:-http://localhost:5001}
      - APP_WEB_URL=${DIFY_APP_WEB_URL:-http://localhost:3000}
      
      # 数据库配置
      - DB_USERNAME=${DIFY_POSTGRES_USER:-dify}
      - DB_PASSWORD=${DIFY_POSTGRES_PASSWORD:-dify123}
      - DB_HOST=dify-postgres
      - DB_PORT=5432
      - DB_DATABASE=${DIFY_POSTGRES_DB:-dify}
      
      # Redis 配置
      - REDIS_HOST=dify-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${DIFY_REDIS_PASSWORD:-dify123}
      - REDIS_DB=0
      - REDIS_USE_SSL=false
      
      # Celery 配置
      - CELERY_BROKER_URL=redis://:${DIFY_REDIS_PASSWORD:-dify123}@dify-redis:6379/1
      
      # 向量数据库配置
      - VECTOR_STORE=weaviate
      - WEAVIATE_ENDPOINT=http://dify-weaviate:8080
      - WEAVIATE_API_KEY=${DIFY_WEAVIATE_API_KEY:-WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih}
      
      # 存储配置
      - STORAGE_TYPE=local
      - STORAGE_LOCAL_PATH=storage
      
      # 代码执行配置
      - CODE_EXECUTION_ENDPOINT=http://dify-sandbox:8194
      - CODE_EXECUTION_API_KEY=${DIFY_SANDBOX_API_KEY:-dify-sandbox}
      
      # 模型配置 (集成VoiceHelper的模型)
      - OPENAI_API_BASE=${OPENAI_API_BASE:-https://api.openai.com/v1}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      
      # 安全配置
      - WEB_API_CORS_ALLOW_ORIGINS=${DIFY_CORS_ALLOW_ORIGINS:-http://localhost:3000,http://localhost:3001}
      - CONSOLE_CORS_ALLOW_ORIGINS=${DIFY_CONSOLE_CORS_ALLOW_ORIGINS:-http://localhost:3001}
      
      # 邮件配置 (可选)
      - MAIL_TYPE=${DIFY_MAIL_TYPE:-}
      - MAIL_DEFAULT_SEND_FROM=${DIFY_MAIL_FROM:-noreply@dify.ai}
      - SMTP_SERVER=${DIFY_SMTP_SERVER:-}
      - SMTP_PORT=${DIFY_SMTP_PORT:-587}
      - SMTP_USERNAME=${DIFY_SMTP_USERNAME:-}
      - SMTP_PASSWORD=${DIFY_SMTP_PASSWORD:-}
      - SMTP_USE_TLS=${DIFY_SMTP_USE_TLS:-true}
      
    ports:
      - "${DIFY_API_PORT:-5001}:5001"
    volumes:
      - dify_api_storage:/app/api/storage
      - dify_api_logs:/app/api/logs
    depends_on:
      dify-postgres:
        condition: service_healthy
      dify-redis:
        condition: service_healthy
      dify-weaviate:
        condition: service_healthy
      dify-sandbox:
        condition: service_healthy
    networks:
      - voicehelper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Dify Worker (后台任务处理)
  dify-worker:
    image: langgenius/dify-api:0.6.16
    container_name: voicehelper-dify-worker
    restart: unless-stopped
    environment:
      # 继承 API 服务的环境变量
      - MODE=worker
      - LOG_LEVEL=${DIFY_LOG_LEVEL:-INFO}
      - SECRET_KEY=${DIFY_SECRET_KEY:-your-dify-secret-key-here}
      
      # 数据库配置
      - DB_USERNAME=${DIFY_POSTGRES_USER:-dify}
      - DB_PASSWORD=${DIFY_POSTGRES_PASSWORD:-dify123}
      - DB_HOST=dify-postgres
      - DB_PORT=5432
      - DB_DATABASE=${DIFY_POSTGRES_DB:-dify}
      
      # Redis 配置
      - REDIS_HOST=dify-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${DIFY_REDIS_PASSWORD:-dify123}
      - REDIS_DB=0
      
      # Celery 配置
      - CELERY_BROKER_URL=redis://:${DIFY_REDIS_PASSWORD:-dify123}@dify-redis:6379/1
      
      # 向量数据库配置
      - VECTOR_STORE=weaviate
      - WEAVIATE_ENDPOINT=http://dify-weaviate:8080
      - WEAVIATE_API_KEY=${DIFY_WEAVIATE_API_KEY:-WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih}
      
      # 存储配置
      - STORAGE_TYPE=local
      - STORAGE_LOCAL_PATH=storage
      
      # 代码执行配置
      - CODE_EXECUTION_ENDPOINT=http://dify-sandbox:8194
      - CODE_EXECUTION_API_KEY=${DIFY_SANDBOX_API_KEY:-dify-sandbox}
      
      # 模型配置
      - OPENAI_API_BASE=${OPENAI_API_BASE:-https://api.openai.com/v1}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      
    volumes:
      - dify_api_storage:/app/api/storage
      - dify_worker_logs:/app/api/logs
    depends_on:
      dify-postgres:
        condition: service_healthy
      dify-redis:
        condition: service_healthy
      dify-weaviate:
        condition: service_healthy
    networks:
      - voicehelper-network
    command: ["celery", "-A", "app.celery", "worker", "-P", "gevent", "-c", "1", "--loglevel=INFO", "-Q", "dataset,generation,mail"]

  # Dify Web Console (管理界面)
  dify-web:
    image: langgenius/dify-web:0.6.16
    container_name: voicehelper-dify-web
    restart: unless-stopped
    environment:
      - CONSOLE_API_URL=${DIFY_CONSOLE_API_URL:-http://localhost:5001}
      - APP_API_URL=${DIFY_SERVICE_API_URL:-http://localhost:5001}
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "${DIFY_WEB_PORT:-3001}:3000"
    depends_on:
      - dify-api
    networks:
      - voicehelper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===========================================
  # 🔗 VoiceHelper-Dify 集成服务
  # ===========================================

  # Dify 集成适配器
  dify-adapter:
    build:
      context: ./integrations/dify-adapter
      dockerfile: Dockerfile
    container_name: voicehelper-dify-adapter
    restart: unless-stopped
    environment:
      # VoiceHelper 连接配置
      - VOICEHELPER_API_URL=http://gateway:8080
      - VOICEHELPER_ALGO_URL=http://algo-service:8000
      
      # Dify 连接配置
      - DIFY_API_URL=http://dify-api:5001
      - DIFY_API_KEY=${DIFY_API_KEY:-app-}
      
      # 适配器配置
      - ADAPTER_PORT=${DIFY_ADAPTER_PORT:-8200}
      - LOG_LEVEL=${DIFY_ADAPTER_LOG_LEVEL:-INFO}
      
      # 数据库配置 (使用主数据库)
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-voicehelper}
      - POSTGRES_USER=${POSTGRES_USER:-voicehelper}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-voicehelper123}
      
      # Redis 配置 (使用主Redis)
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis123}
      
    ports:
      - "${DIFY_ADAPTER_PORT:-8200}:8200"
    volumes:
      - dify_adapter_logs:/app/logs
    depends_on:
      - gateway
      - algo-service
      - dify-api
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - voicehelper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ===========================================
  # 🔧 Dify 管理工具
  # ===========================================

  # Dify 数据库管理
  dify-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: voicehelper-dify-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: dify-admin@voicehelper.ai
      PGADMIN_DEFAULT_PASSWORD: dify123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${DIFY_PGADMIN_PORT:-5051}:80"
    volumes:
      - dify_pgadmin_data:/var/lib/pgadmin
      - ./tools/deployment/dify/pgadmin-servers.json:/pgadmin4/servers.json
    depends_on:
      - dify-postgres
    networks:
      - voicehelper-network
    profiles:
      - dify-tools

  # Dify Redis 管理
  dify-redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: voicehelper-dify-redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=dify:dify-redis:6379:0:${DIFY_REDIS_PASSWORD:-dify123}
    ports:
      - "${DIFY_REDIS_COMMANDER_PORT:-8083}:8081"
    depends_on:
      - dify-redis
    networks:
      - voicehelper-network
    profiles:
      - dify-tools

# ===========================================
# 🌐 网络配置 (扩展现有网络)
# ===========================================
networks:
  voicehelper-network:
    external: true

# ===========================================
# 💾 Dify 数据卷配置
# ===========================================
volumes:
  # Dify 数据库数据卷
  dify_postgres_data:
    driver: local
  dify_redis_data:
    driver: local
  dify_weaviate_data:
    driver: local
  
  # Dify 应用数据卷
  dify_api_storage:
    driver: local
  dify_api_logs:
    driver: local
  dify_worker_logs:
    driver: local
  dify_sandbox_data:
    driver: local
  
  # Dify 集成数据卷
  dify_adapter_logs:
    driver: local
  
  # Dify 管理工具数据卷
  dify_pgadmin_data:
    driver: local
