global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (系统监控)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor (容器监控)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Gateway服务监控
  - job_name: 'chatbot-gateway'
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Algorithm服务监控
  - job_name: 'chatbot-algo'
    static_configs:
      - targets: ['algo:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL监控
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # Milvus监控
  - job_name: 'milvus'
    static_configs:
      - targets: ['milvus:9091']
    metrics_path: '/metrics'

  # Neo4j监控
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:2004']
    metrics_path: '/metrics'

  # RabbitMQ监控
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'

  # Elasticsearch监控
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
