# VoiceHelper 应用服务部署配置 - 最小资源版本

# Go 后端网关服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: voicehelper
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: backend
    app.kubernetes.io/version: "2.0"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
        app.kubernetes.io/component: backend
        app.kubernetes.io/version: "2.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: voicehelper-sa
      initContainers:
      - name: wait-for-dependencies
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for PostgreSQL..."
          until nc -z postgresql-service 5432; do sleep 2; done
          echo "Waiting for Redis..."
          until nc -z redis-service 6379; do sleep 2; done
          echo "Waiting for BGE service..."
          until nc -z bge-service 8080; do sleep 2; done
          echo "Waiting for FAISS service..."
          until nc -z faiss-service 8081; do sleep 2; done
          echo "All dependencies are ready"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      containers:
      - name: gateway
        image: voicehelper/gateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
          name: grpc
          protocol: TCP
        envFrom:
        - configMapRef:
            name: voicehelper-config
        - secretRef:
            name: voicehelper-secrets
        env:
        - name: SERVICE_NAME
          value: "gateway"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: logs
          mountPath: /var/log/voicehelper
        - name: config
          mountPath: /etc/voicehelper
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
      volumes:
      - name: logs
        emptyDir: {}
      - name: config
        configMap:
          name: gateway-config

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: voicehelper
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app.kubernetes.io/name: gateway
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: grpc
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP

---
# Gateway 配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: voicehelper
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080
      grpc_port: 8081
      read_timeout: 30s
      write_timeout: 30s
      idle_timeout: 60s
      max_header_bytes: 1048576
    
    database:
      host: postgresql-service
      port: 5432
      name: voicehelper
      ssl_mode: disable
      max_open_conns: 50
      max_idle_conns: 5
      conn_max_lifetime: 3600s
    
    redis:
      host: redis-service
      port: 6379
      db: 0
      max_retries: 3
      pool_size: 50
      min_idle_conns: 5
    
    vector_services:
      bge_service_url: http://bge-service:8080
      faiss_service_url: http://faiss-service:8081
    
    nats:
      url: nats://nats-service:4222
      cluster_id: voicehelper-cluster
    
    services:
      algo_service_url: http://algo-service:8000
      voice_service_url: http://voice-service:8001
    
    security:
      cors_allowed_origins: ["*"]
      rate_limit_enabled: true
      rate_limit_requests: 100
      rate_limit_window: 60s
    
    monitoring:
      metrics_enabled: true
      tracing_enabled: true
      jaeger_endpoint: http://jaeger-collector.voicehelper-monitoring:14268/api/traces

---
# Python 算法服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: algo-service
  namespace: voicehelper
  labels:
    app.kubernetes.io/name: algo-service
    app.kubernetes.io/component: algorithm
    app.kubernetes.io/version: "2.0"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: algo-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: algo-service
        app.kubernetes.io/component: algorithm
        app.kubernetes.io/version: "2.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: voicehelper-sa
      initContainers:
      - name: wait-for-dependencies
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for BGE service..."
          until nc -z bge-service 8080; do sleep 2; done
          echo "Waiting for FAISS service..."
          until nc -z faiss-service 8081; do sleep 2; done
          echo "Waiting for Redis..."
          until nc -z redis-service 6379; do sleep 2; done
          echo "Dependencies are ready"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      containers:
      - name: algo-service
        image: voicehelper/algo-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: voicehelper-config
        - secretRef:
            name: voicehelper-secrets
        env:
        - name: SERVICE_NAME
          value: "algo-service"
        - name: PYTHONPATH
          value: "/app"
        - name: WORKERS
          value: "2"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: logs
          mountPath: /var/log/voicehelper
        - name: temp
          mountPath: /tmp
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 60
      volumes:
      - name: logs
        emptyDir: {}
      - name: temp
        emptyDir:
          sizeLimit: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: algo-service
  namespace: voicehelper
  labels:
    app.kubernetes.io/name: algo-service
    app.kubernetes.io/component: algorithm
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app.kubernetes.io/name: algo-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

---
# 前端服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: voicehelper
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web
    app.kubernetes.io/version: "2.0"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/component: web
        app.kubernetes.io/version: "2.0"
    spec:
      serviceAccountName: voicehelper-sa
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: voicehelper
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
  - name: http
    port: 3000
    targetPort: 80
    protocol: TCP
  type: ClusterIP

---
# 语音服务
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-service
  namespace: voicehelper
  labels:
    app.kubernetes.io/name: voice-service
    app.kubernetes.io/component: voice
    app.kubernetes.io/version: "2.0"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: voice-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: voice-service
        app.kubernetes.io/component: voice
        app.kubernetes.io/version: "2.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: voicehelper-sa
      containers:
      - name: voice-service
        image: python:3.11-slim
        ports:
        - containerPort: 8001
          name: http
          protocol: TCP
        - containerPort: 8002
          name: websocket
          protocol: TCP
        envFrom:
        - configMapRef:
            name: voicehelper-config
        - secretRef:
            name: voicehelper-secrets
        env:
        - name: SERVICE_NAME
          value: "voice-service"
        - name: PYTHONPATH
          value: "/app"
        command: ["python", "-c", "import time; print('Voice service placeholder'); time.sleep(3600)"]
        volumeMounts:
        - name: audio-cache
          mountPath: /tmp/audio
        - name: logs
          mountPath: /var/log/voicehelper
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: audio-cache
        emptyDir:
          sizeLimit: 2Gi
      - name: logs
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: voice-service
  namespace: voicehelper
  labels:
    app.kubernetes.io/name: voice-service
    app.kubernetes.io/component: voice
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8001"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app.kubernetes.io/name: voice-service
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    protocol: TCP
  - name: websocket
    port: 8002
    targetPort: 8002
    protocol: TCP
  type: ClusterIP
