# 修复FAISS服务的PV配置
apiVersion: v1
kind: PersistentVolume
metadata:
  name: faiss-data-pv-fixed
  labels:
    app.kubernetes.io/name: faiss-service
    app.kubernetes.io/component: vector-search
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: voicehelper-ssd
  hostPath:
    path: /Users/lintao/voicehelper-storage/faiss
    type: DirectoryOrCreate
