# Milvus 向量数据库 Kubernetes 部署配置

# Milvus etcd
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-etcd
  namespace: voicehelper
  labels:
    app: milvus-etcd
    component: milvus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus-etcd
  template:
    metadata:
      labels:
        app: milvus-etcd
        component: milvus
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.5
        ports:
        - containerPort: 2379
        - containerPort: 2380
        env:
        - name: ETCD_AUTO_COMPACTION_MODE
          value: "revision"
        - name: ETCD_AUTO_COMPACTION_RETENTION
          value: "1000"
        - name: ETCD_QUOTA_BACKEND_BYTES
          value: "4294967296"
        - name: ETCD_SNAPSHOT_COUNT
          value: "50000"
        command:
        - etcd
        - -advertise-client-urls=http://127.0.0.1:2379
        - -listen-client-urls=http://0.0.0.0:2379
        - --data-dir=/etcd
        volumeMounts:
        - name: etcd-storage
          mountPath: /etcd
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - etcdctl
            - endpoint
            - health
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - etcdctl
            - endpoint
            - health
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: etcd-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: milvus-etcd-service
  namespace: voicehelper
  labels:
    app: milvus-etcd
spec:
  selector:
    app: milvus-etcd
  ports:
  - port: 2379
    targetPort: 2379
    protocol: TCP
  type: ClusterIP
---
# Milvus MinIO
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-minio
  namespace: voicehelper
  labels:
    app: milvus-minio
    component: milvus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus-minio
  template:
    metadata:
      labels:
        app: milvus-minio
        component: milvus
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2023-03-20T20-16-18Z
        ports:
        - containerPort: 9000
        - containerPort: 9001
        env:
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        command:
        - minio
        - server
        - /minio_data
        - --console-address
        - ":9001"
        volumeMounts:
        - name: minio-storage
          mountPath: /minio_data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: minio-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: milvus-minio-service
  namespace: voicehelper
  labels:
    app: milvus-minio
spec:
  selector:
    app: milvus-minio
  ports:
  - name: api
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: console
    port: 9001
    targetPort: 9001
    protocol: TCP
  type: ClusterIP
---
# Milvus Standalone
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus
  namespace: voicehelper
  labels:
    app: milvus
    component: vector-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
        component: vector-database
    spec:
      containers:
      - name: milvus
        image: milvusdb/milvus:v2.3.3
        ports:
        - containerPort: 19530
        - containerPort: 9091
        env:
        - name: ETCD_ENDPOINTS
          value: "milvus-etcd-service:2379"
        - name: MINIO_ADDRESS
          value: "milvus-minio-service:9000"
        command:
        - milvus
        - run
        - standalone
        volumeMounts:
        - name: milvus-storage
          mountPath: /var/lib/milvus
        - name: milvus-config
          mountPath: /milvus/configs
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "8Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9091
          initialDelaySeconds: 90
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9091
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: milvus-storage
        persistentVolumeClaim:
          claimName: milvus-pvc
      - name: milvus-config
        configMap:
          name: milvus-config
      initContainers:
      - name: wait-for-etcd
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          until nc -z milvus-etcd-service 2379; do
            echo "Waiting for etcd..."
            sleep 2
          done
      - name: wait-for-minio
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          until nc -z milvus-minio-service 9000; do
            echo "Waiting for minio..."
            sleep 2
          done
---
apiVersion: v1
kind: Service
metadata:
  name: milvus-service
  namespace: voicehelper
  labels:
    app: milvus
spec:
  selector:
    app: milvus
  ports:
  - name: grpc
    port: 19530
    targetPort: 19530
    protocol: TCP
  - name: metrics
    port: 9091
    targetPort: 9091
    protocol: TCP
  type: ClusterIP
---
# Milvus 配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: milvus-config
  namespace: voicehelper
data:
  milvus.yaml: |
    # Milvus 配置文件
    etcd:
      endpoints:
        - milvus-etcd-service:2379
    
    minio:
      address: milvus-minio-service
      port: 9000
      accessKeyID: minioadmin
      secretAccessKey: minioadmin
      useSSL: false
      bucketName: "a-bucket"
      rootPath: "files"
    
    pulsar:
      address: localhost
      port: 6650
    
    rocksmq:
      path: /var/lib/milvus/rdb_data
    
    storage:
      path: /var/lib/milvus/data/
    
    log:
      level: info
      file:
        rootPath: /var/lib/milvus/logs
    
    grpc:
      serverMaxRecvSize: 268435456
      serverMaxSendSize: 268435456
      clientMaxRecvSize: 268435456
      clientMaxSendSize: 268435456
    
    common:
      defaultPartitionName: "_default"
      defaultIndexName: "_default_idx"
      retentionDuration: 432000
      entityExpiration: -1
      indexSliceSize: 16
    
    quotaAndLimits:
      enabled: true
      quotaCenterCollectInterval: 3
      quotaTTL: 7
      limitWriting:
        ttProtection:
          enabled: false
        memProtection:
          enabled: true
        diskProtection:
          enabled: true
      limitReading:
        queueProtection:
          enabled: false
        resultProtection:
          enabled: false
