# 简化的Gateway服务，不依赖BGE和FAISS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-simple
  namespace: voicehelper
  labels:
    app.kubernetes.io/name: gateway-simple
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-simple
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway-simple
        app.kubernetes.io/component: backend
    spec:
      serviceAccountName: voicehelper-sa
      initContainers:
      - name: wait-for-dependencies
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for PostgreSQL..."
          until nc -z postgresql-service 5432; do sleep 2; done
          echo "Waiting for Redis..."
          until nc -z redis-service 6379; do sleep 2; done
          echo "Basic dependencies are ready"
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      containers:
      - name: gateway
        image: voicehelper/gateway:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: voicehelper-config
        - secretRef:
            name: voicehelper-secrets
        env:
        - name: SERVICE_NAME
          value: "gateway-simple"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-simple-service
  namespace: voicehelper
  labels:
    app.kubernetes.io/name: gateway-simple
spec:
  selector:
    app.kubernetes.io/name: gateway-simple
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

---
# 简单的Ingress配置
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voicehelper-ingress
  namespace: voicehelper
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: voicehelper.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: gateway-simple-service
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 3000
