global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'voicehelper-gateway'
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'voicehelper-algo'
    static_configs:
      - targets: ['algo-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'voicehelper-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 10s

  - job_name: 'voicehelper-admin'
    static_configs:
      - targets: ['admin:5001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:7474']

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
